-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 15:43:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TuZik?
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TuZik?` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `TuZik?` ;

-- -----------------------------------------------------
-- Table `TuZik?`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`utilisateur` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(50) NULL DEFAULT NULL,
  `Prenom` VARCHAR(50) NULL DEFAULT NULL,
  `telephone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `motdepasse` VARCHAR(32) NOT NULL,
  `Num Magasin` VARCHAR(45) NOT NULL DEFAULT 0,
  `Num Fabricant` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuZik?`.`profilMagasin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`profilMagasin` (
  `NumMagasin` INT NOT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `horaires` VARCHAR(45) NULL DEFAULT NULL,
  `utilisateur_id` BIGINT NOT NULL,
  PRIMARY KEY (`NumMagasin`),
  CONSTRAINT `fk_profilMagasin_utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `TuZik?`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TuZik?`.`profil fabricant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`profil fabricant` (
  `NumFabricant` INT NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  `spécialité` VARCHAR(45) NULL,
  `prix` FLOAT NULL,
  `utilisateurid` BIGINT NULL,
  PRIMARY KEY (`NumFabricant`),
  CONSTRAINT `utilisateurid`
    FOREIGN KEY (`utilisateurid`)
    REFERENCES `TuZik?`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuZik?`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`categorie` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parentId` BIGINT NULL DEFAULT NULL,
  `Titre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `parentid`
    FOREIGN KEY (`parentId`)
    REFERENCES `TuZik?`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuZik?`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`produit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `utilisateur_Id` BIGINT NOT NULL,
  `Titre` VARCHAR(75) NOT NULL,
  `type` SMALLINT(6) NOT NULL DEFAULT 0,
  `prix` FLOAT NOT NULL DEFAULT 0,
  `idCategorie` BIGINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_produit_utilisateur`
    FOREIGN KEY (`utilisateur_Id`)
    REFERENCES `TuZik?`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategorie`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `TuZik?`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuZik?`.`panier_objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`panier_objet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `produitId` BIGINT NOT NULL,
  `userId` BIGINT NOT NULL,
  `quantite` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_panier_objet_produit`
    FOREIGN KEY (`produitId`)
    REFERENCES `TuZik?`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `TuZik?`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TuZik?`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`Commande` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NULL DEFAULT NULL,
  `sessionId` VARCHAR(100) NOT NULL,
  `shipping` FLOAT NOT NULL DEFAULT 0,
  `total` FLOAT NOT NULL DEFAULT 0,
  `grandTotal` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commande_utilisateur`
    FOREIGN KEY (`userId`)
    REFERENCES `TuZik?`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TuZik?`.`Commande_objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`Commande_objet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `produitId` BIGINT NOT NULL,
  `CommandeId` BIGINT NOT NULL,
  `quantité` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commande_objet_produit`
    FOREIGN KEY (`produitId`)
    REFERENCES `TuZik?`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_objet_Commande`
    FOREIGN KEY (`CommandeId`)
    REFERENCES `TuZik?`.`Commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TuZik?`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TuZik?`.`paiement` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `CommandeId` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `type` SMALLINT(6) NOT NULL DEFAULT 0,
  `mode` SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `code`, `type`),
  CONSTRAINT `fk_paiement_commande`
    FOREIGN KEY (`CommandeId`)
    REFERENCES `TuZik?`.`Commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
